*SRCMBRTXT:LINK-GDE-Prototipos de Funciones Comune
**free

//=====================================================================
// Estructuras de Datos
//=====================================================================

//Estructura de datos de estado de Programa
dcl-ds pgm_stat PSDS qualified;
        exception_type   char(3) pos(40);
        exception_number char(4) pos(43);
end-ds;

//----------------------------------------------------------------------
//DATASTRUCTURE : SYSERR
//DESCRIPTION   : Data structure to receive error generated by OPM APIS
//USE           : Retrieve OPM API Error codes
//RELATEDFUNCT  : sysSndPgmMsg
//----------------------------------------------------------------------
 /IF NOT DEFINED(SYSERR_DEFINED)
 /DEFINE SYSERR_DEFINED
dcl-ds SYSERR ;
    dsECBytesP             int(5) inz(256) ;
    dsECBytesA             int(5) inz(0) ;
    dsECMsgID              char(7) ;
    dsECReserv             char(1) ;
    dsECMsgDta             char(239);
 end-ds ;
 /ENDIF

//=====================================================================
// Procedimientos =>  API Wrappers
//=====================================================================
dcl-pr exeCmd char(7);
    cmd_str  char(4096) const;
end-pr;

dcl-pr getRefreshFileName char(29);
    p_Servicio char(2) const;
    p_TipoServ char(2) const;
end-pr;

dcl-pr sndPgmMsg char(4);
    msg_id      char(7) const ;
    msg_file    char(20) const options(*nopass);
    msg_data    char(256) const options(*nopass);
    msg_type    char(10) const options(*nopass);
end-pr;

dcl-pr die ;
    msg_str     char(256) const;
end-pr;

dcl-pr wrtToJobLog ;
    msg_str     char(256) const;
end-pr;

//=====================================================================
// Procedimientos =>  IFS Wrappers
//=====================================================================
dcl-pr ifs_stmf_opnwrt int(10);
  fqn varchar(255) const;
end-pr;

dcl-pr ifs_stmf_close;
  fd int(10) const;
end-pr;

dcl-pr ifs_wrtln;
  fd int(10) const;
  line varchar(MAX_FILE_SIZE) const;
end-pr;

dcl-pr ifs_readln int(10);
    fd int(10) const;
    line varchar(MAX_FILE_SIZE);
end-pr;

dcl-pr ifs_readln_dos int(10);
    fd int(10) const;
    line varchar(MAX_FILE_SIZE);
end-pr;
//=====================================================================
// Procedimientos =>  APIs SIDEBA
//=====================================================================

dcl-pr bco_get_sfei packed(8:0);
end-pr;

dcl-pr bco_get_cbu packed(22:0);
        tipo    char(1);
        isuc    packed(5:0);
        icta    packed(11:0);
end-pr;

